window.esdocSearchIndex = [
  [
    "javascript/engine/models/building.js~building",
    "class/engine/models/Building.js~Building.html",
    "<span>Building</span> <span class=\"search-result-import-path\">javascript/engine/models/Building.js</span>",
    "class"
  ],
  [
    "javascript/engine/models/currency.js~currency",
    "class/engine/models/Currency.js~Currency.html",
    "<span>Currency</span> <span class=\"search-result-import-path\">javascript/engine/models/Currency.js</span>",
    "class"
  ],
  [
    "javascript/engine/handlers/currencyhandler.js~currencyhandler",
    "class/engine/handlers/CurrencyHandler.js~CurrencyHandler.html",
    "<span>CurrencyHandler</span> <span class=\"search-result-import-path\">javascript/engine/handlers/CurrencyHandler.js</span>",
    "class"
  ],
  [
    "javascript/engine/models/currencylist.js~currencylist",
    "class/engine/models/CurrencyList.js~CurrencyList.html",
    "<span>CurrencyList</span> <span class=\"search-result-import-path\">javascript/engine/models/CurrencyList.js</span>",
    "class"
  ],
  [
    "javascript/engine/models/player.js~player",
    "class/engine/models/Player.js~Player.html",
    "<span>Player</span> <span class=\"search-result-import-path\">javascript/engine/models/Player.js</span>",
    "class"
  ],
  [
    "javascript/engine/models/wallet.js~wallet",
    "class/engine/models/Wallet.js~Wallet.html",
    "<span>Wallet</span> <span class=\"search-result-import-path\">javascript/engine/models/Wallet.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "engine/handlers/currencyhandler.js",
    "file/engine/handlers/CurrencyHandler.js.html",
    "engine/handlers/CurrencyHandler.js",
    "file"
  ],
  [
    "engine/handlers/currencyhandler.js~currencyhandler#constructor",
    "class/engine/handlers/CurrencyHandler.js~CurrencyHandler.html#instance-constructor-constructor",
    "engine/handlers/CurrencyHandler.js~CurrencyHandler#constructor",
    "method"
  ],
  [
    "engine/handlers/currencyhandler.js~currencyhandler#currencytohandle",
    "class/engine/handlers/CurrencyHandler.js~CurrencyHandler.html#instance-member-currencyToHandle",
    "engine/handlers/CurrencyHandler.js~CurrencyHandler#currencyToHandle",
    "member"
  ],
  [
    "engine/handlers/currencyhandler.js~currencyhandler#decrementcurrrency",
    "class/engine/handlers/CurrencyHandler.js~CurrencyHandler.html#instance-method-decrementCurrrency",
    "engine/handlers/CurrencyHandler.js~CurrencyHandler#decrementCurrrency",
    "method"
  ],
  [
    "engine/handlers/currencyhandler.js~currencyhandler#incrementcurrency",
    "class/engine/handlers/CurrencyHandler.js~CurrencyHandler.html#instance-method-incrementCurrency",
    "engine/handlers/CurrencyHandler.js~CurrencyHandler#incrementCurrency",
    "method"
  ],
  [
    "engine/models/building.js",
    "file/engine/models/Building.js.html",
    "engine/models/Building.js",
    "file"
  ],
  [
    "engine/models/building.js~building#constuctor",
    "class/engine/models/Building.js~Building.html#instance-method-constuctor",
    "engine/models/Building.js~Building#constuctor",
    "method"
  ],
  [
    "engine/models/currency.js",
    "file/engine/models/Currency.js.html",
    "engine/models/Currency.js",
    "file"
  ],
  [
    "engine/models/currency.js~currency#add",
    "class/engine/models/Currency.js~Currency.html#instance-method-add",
    "engine/models/Currency.js~Currency#add",
    "method"
  ],
  [
    "engine/models/currency.js~currency#constructor",
    "class/engine/models/Currency.js~Currency.html#instance-constructor-constructor",
    "engine/models/Currency.js~Currency#constructor",
    "method"
  ],
  [
    "engine/models/currency.js~currency#handler",
    "class/engine/models/Currency.js~Currency.html#instance-member-handler",
    "engine/models/Currency.js~Currency#handler",
    "member"
  ],
  [
    "engine/models/currency.js~currency#name",
    "class/engine/models/Currency.js~Currency.html#instance-member-name",
    "engine/models/Currency.js~Currency#name",
    "member"
  ],
  [
    "engine/models/currency.js~currency#subtract",
    "class/engine/models/Currency.js~Currency.html#instance-method-subtract",
    "engine/models/Currency.js~Currency#subtract",
    "method"
  ],
  [
    "engine/models/currencylist.js",
    "file/engine/models/CurrencyList.js.html",
    "engine/models/CurrencyList.js",
    "file"
  ],
  [
    "engine/models/currencylist.js~currencylist#addcurrency",
    "class/engine/models/CurrencyList.js~CurrencyList.html#instance-method-addCurrency",
    "engine/models/CurrencyList.js~CurrencyList#addCurrency",
    "method"
  ],
  [
    "engine/models/currencylist.js~currencylist#constructor",
    "class/engine/models/CurrencyList.js~CurrencyList.html#instance-constructor-constructor",
    "engine/models/CurrencyList.js~CurrencyList#constructor",
    "method"
  ],
  [
    "engine/models/currencylist.js~currencylist#list",
    "class/engine/models/CurrencyList.js~CurrencyList.html#instance-member-list",
    "engine/models/CurrencyList.js~CurrencyList#list",
    "member"
  ],
  [
    "engine/models/currencylist.js~currencylist#listofcurrencies",
    "class/engine/models/CurrencyList.js~CurrencyList.html#instance-get-listOfCurrencies",
    "engine/models/CurrencyList.js~CurrencyList#listOfCurrencies",
    "member"
  ],
  [
    "engine/models/player.js",
    "file/engine/models/Player.js.html",
    "engine/models/Player.js",
    "file"
  ],
  [
    "engine/models/player.js~player#constructor",
    "class/engine/models/Player.js~Player.html#instance-constructor-constructor",
    "engine/models/Player.js~Player#constructor",
    "method"
  ],
  [
    "engine/models/player.js~player#name",
    "class/engine/models/Player.js~Player.html#instance-member-name",
    "engine/models/Player.js~Player#name",
    "member"
  ],
  [
    "engine/models/player.js~player#viewwallet",
    "class/engine/models/Player.js~Player.html#instance-method-viewWallet",
    "engine/models/Player.js~Player#viewWallet",
    "method"
  ],
  [
    "engine/models/player.js~player#wallet",
    "class/engine/models/Player.js~Player.html#instance-member-wallet",
    "engine/models/Player.js~Player#wallet",
    "member"
  ],
  [
    "engine/models/wallet.js",
    "file/engine/models/Wallet.js.html",
    "engine/models/Wallet.js",
    "file"
  ],
  [
    "engine/models/wallet.js~wallet#constructor",
    "class/engine/models/Wallet.js~Wallet.html#instance-constructor-constructor",
    "engine/models/Wallet.js~Wallet#constructor",
    "method"
  ],
  [
    "engine/models/wallet.js~wallet#currencies",
    "class/engine/models/Wallet.js~Wallet.html#instance-member-currencies",
    "engine/models/Wallet.js~Wallet#currencies",
    "member"
  ],
  [
    "engine/models/wallet.js~wallet#decrementcurrrency",
    "class/engine/models/Wallet.js~Wallet.html#instance-method-decrementCurrrency",
    "engine/models/Wallet.js~Wallet#decrementCurrrency",
    "method"
  ],
  [
    "engine/models/wallet.js~wallet#incrementcurrency",
    "class/engine/models/Wallet.js~Wallet.html#instance-method-incrementCurrency",
    "engine/models/Wallet.js~Wallet#incrementCurrency",
    "method"
  ],
  [
    "engine/models/wallet.js~wallet#view",
    "class/engine/models/Wallet.js~Wallet.html#instance-method-view",
    "engine/models/Wallet.js~Wallet#view",
    "method"
  ]
]